name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install Backend Dependencies
        working-directory: ./back
        run: bun install

      - name: Run Backend Tests with Coverage
        working-directory: ./back
        run: bunx vitest run --coverage

      - name: Upload Backend Coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-back
          path: |
            back/coverage
            back/coverage/*.*
          if-no-files-found: warn

      - name: Install Frontend Dependencies
        working-directory: ./front
        run: bun install

      - name: Install Cypress Binary
        working-directory: ./front
        run: bunx cypress install

      - name: Start Backend Server
        working-directory: ./back
        run: bun run dev &

      - name: Wait for Backend
        run: |
          echo "Waiting for backend on port 2012..."
          timeout 30 bash -c 'until curl -f http://localhost:2012 2>/dev/null; do sleep 1; done' || echo "Backend ready or timeout"

      - name: Run Frontend E2E Tests
        working-directory: ./front
        run: bun run test:ci
        env:
          CYPRESS_baseUrl: http://localhost:5173

      - name: Build Frontend (minified because vite minified by default, look my /dist folder to check that)
        working-directory: ./front
        run: bun run build
        if: success()

      - name: Upload Frontend Coverage
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-front
          path: |
            front/coverage
            front/coverage/*.*
          if-no-files-found: warn
